//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonBallMatching
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Dragon_Ball_MatchingEntities : DbContext
    {
        public Dragon_Ball_MatchingEntities()
            : base("name=Dragon_Ball_MatchingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AreaTable> AreaTables { get; set; }
        public virtual DbSet<ImagesTable> ImagesTables { get; set; }
        public virtual DbSet<LikesTable> LikesTables { get; set; }
        public virtual DbSet<MessagesTable> MessagesTables { get; set; }
        public virtual DbSet<SexTable> SexTables { get; set; }
        public virtual DbSet<UsersTable> UsersTables { get; set; }
        public virtual DbSet<LogonTable> LogonTables { get; set; }
    }
}
