//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonBallMatching
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogonTable
    {
        public int UserID { get; set; }
        public string Username { get; set; }
        public string PWD { get; set; }
    
        public virtual UsersTable UsersTable { get; set; }
    }
}
