//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonBallMatching
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessagesTable
    {
        public string Messages { get; set; }
        public string Sender_message { get; set; }
        public string reciever_message { get; set; }
        public Nullable<bool> IsRead_message { get; set; }
        public System.DateTime StartDate_message { get; set; }
    }
}
